# Generated by Django 4.0.5 on 2023-02-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
