# Generated by Django 4.0.5 on 2023-02-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payement_intent',
            new_name='payment_intent',
        ),
    ]
