# Generated by Django 4.0.5 on 2023-02-28 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/vendor_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
