# Generated by Django 4.0.5 on 2023-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_vendor_vendor_address_vendor_vendor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='no_of_product',
            field=models.IntegerField(null=True),
        ),
    ]
