# Generated by Django 4.1.7 on 2023-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.IntegerField(null=True),
        ),
    ]
