# Generated by Django 4.1.7 on 2023-03-14 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_product_average_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
    ]
