# Generated by Django 4.0.5 on 2023-03-21 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem', to=settings.AUTH_USER_MODEL),
        ),
    ]
