# Generated by Django 4.0.5 on 2023-03-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
    ]
