# Generated by Django 4.0.5 on 2023-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_admin_paid_to_vendor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
