# Generated by Django 4.0.5 on 2023-04-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
