# Generated by Django 4.1.7 on 2023-03-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_vendor_income_alter_vendor_no_of_product"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermessage",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="store.vendor",
            ),
        ),
    ]
