# Generated by Django 4.0.5 on 2023-04-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_adminmessage_providermessage_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='sp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='ProviderMessage',
        ),
    ]
