# Generated by Django 4.0.5 on 2023-04-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprovider_sp_email_delete_providermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='sp_video',
            field=models.FileField(null=True, upload_to='uploads/service_video/'),
        ),
    ]
