# Generated by Django 4.0.5 on 2023-04-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_serviceprovider_sp_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='sp_image',
            field=models.ImageField(blank=True, upload_to='uploads/service_provider_image/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/service_image/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='video',
            field=models.FileField(blank=True, upload_to='uploads/service_video/'),
        ),
    ]
