# Generated by Django 4.0.5 on 2023-04-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceprovider_sp_image_alter_services_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='sp_contact',
            field=models.TextField(),
        ),
    ]
