# Generated by Django 4.0.5 on 2023-03-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BecomeVendor',
        ),
    ]
