# Generated by Django 4.1.7 on 2023-03-14 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BecomeVendor",
        ),
    ]
