# Generated by Django 4.0.5 on 2023-03-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_delete_becomevendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
