# Generated by Django 4.0.5 on 2023-03-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='forget_password',
        ),
    ]
